import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Switch from '../components/Switch'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FCC Switch Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the FCC
        </h1>

        <p className={styles.description}>
          Until we have a state machine, the buttons will just call the <code className={styles.code}>on</code> and <code className={styles.code}>off</code> functions
        </p>

        <div className={styles.grid}>
          <Switch switchName="Air conditioner" switchNumber="13" />
          <Switch switchName="Wobbly lamp" switchNumber="11" />
        </div>
      </main>
    </div>
  )
}
